name: Boundary

on:
  schedule:
  - cron: '0 4 * * 6'
  workflow_dispatch:

jobs:
  poly:
    if: github.repository == 'osm-fr/osmose-backend'
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Setup env
      run: |
        # configure paths used for tmp files
        sudo mkdir -p /data/work/$USER /data/work/$USER/cache
        sudo chown $USER /data/work/$USER /data/work/$USER/cache

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyproj requests shapely

    - name: Compare polygons and relations
      run: |
        python -m tools.check-boundary-polygon
